# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Font-TTF-Scripts
version:      0.10
version_from: 
installdirs:  site
requires:
    Algorithm::Diff:               0
    Font::TTF:                     0.42
    Parse::RecDescent:             1.51
    Text::PDF::File:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
